apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-custom-template
  title: Registro de Sub Etapa
  description: Crea una Sub Etapa para enlazar con un componente técnico comun
  tags:
    - Sub Etapa
    - Componente Comun
spec:
  owner: group:default/juan-manuel-perez
  type: service

  parameters:
    - title: Nombre de la Sub Etapa
      required:
        - name
      properties:
        name:
          title: Nombre
          type: string
          description: Nombre unico de la Sub Etapa
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is ${{ parameters.name }}'
        repoUrl: https://github.com/organizationjc/backstage-catalog/blob/main/catalog/templates/my-custom-template/template.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}