apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Template-Para-Registro-Sub-Etapa
  title: Registro de Sub Etapa
  description: Crea una Sub Etapa para enlazar con un componente técnico comun
  tags:
    - sub-etapa
    - componente-comun
spec:
  owner: group:default/juan-manuel-perez
  type: service

  parameters:
    - title: Nombre de la Sub Etapa
      required:
        - name
      properties:
        name:
          title: Nombre
          type: string
          description: Nombre unico de la Sub Etapa
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is ${{ parameters.name }}'
        repoUrl: >-
          github.com?repo=${{ parameters.name | lower | replace(" ", "-") | normalize }}-${{ uuid | slice(0, 6) }}&owner=organizationjc

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}